import os

env_path = ".env"
env_js_path = "extension/env.js"

api_endpoint = ""

if os.path.exists(env_path):
    with open(env_path, "r") as f:
        for line in f:
            line = line.strip()
            if line.startswith("API_ENDPOINT="):
                api_endpoint = line.split("=", 1)[1].strip()
                break

if not api_endpoint:
    print("Warning: API_ENDPOINT not found in .env, using default.")
    api_endpoint = "http://localhost:8000/api/events"

with open(env_js_path, "w") as f:
    f.write(f'// Auto-generated by sync_env.py. Do not edit directly.\n')
    f.write(f'var API_ENDPOINT = "{api_endpoint}";\n')

print(f"Successfully updated {env_js_path} with API_ENDPOINT = {api_endpoint}")
